### ISSUE TITLE
Unable to create workable universal hex

### ISSUE THREAD

**Issue by thegecko** [microbit-foundation/microbit-universal-hex#20]
Using this library I've tried creating a universal hex from existing v1 and v2 hex files which are known to work.

I could be driving it incorrectly, but pulled together a basic CLI to do this (PR imminent):

https://github.com/microbit-foundation/microbit-universal-hex/compare/master...thegecko:master#diff-bed707abb0f057cc86f9e362bd696dd3R22

I initially hit [this error](https://github.com/microbit-foundation/microbit-universal-hex/blob/master/src/universal-hex.ts#L135), but got it to succeed by commenting out this check (in this case I was assuming the hex file is correct, after all it woks!)

Once the universal hex file was created, neither v1 nor v2 boards would flash and run.

The v1 hex is an old app I wrote using yotta and the v2 hex is recent using codal. Files as follows:

[v1.hex.txt](https://github.com/microbit-foundation/microbit-universal-hex/files/5362255/v1.hex.txt)
[v2.hex.txt](https://github.com/microbit-foundation/microbit-universal-hex/files/5362257/v2.hex.txt)
[universal.hex.txt](https://github.com/microbit-foundation/microbit-universal-hex/files/5362258/universal.hex.txt)

**Comment by microbit-carlos** [comment]
Sorry for the late reply @thegecko, and thanks @martinwork for all your help here as well, hopefully this can still be useful.

-----

> I initially hit [this error](https://github.com/microbit-foundation/microbit-universal-hex/blob/master/src/universal-hex.ts#L135), but got it to succeed by commenting out this check (in this case I was assuming the hex file is correct, after all it woks!)


Assuming that was linking to this:
https://github.com/microbit-foundation/microbit-universal-hex/blob/f3bb456f9cb7b6f4b6b87ff8f104fd7d6944a2eb/src/universal-hex.ts#L135


The current version of the library expects the Intel Hex files to end with an End Of File record.
This means that some MakeCode files that include records after the EoF record will be rejected, but this is not the case in the files you attached.

As Martin mentioned an interesting difference is that the v2.hex has windows endings, but technically this should have worked fine, as the hex file is first separated in lined with `ihex. iHexToRecordStrs()`, and that should work with either line ending: https://github.com/microbit-foundation/microbit-universal-hex/blob/508a60562e19cb6c4b9d0bfe012e6bf2882dca9e/src/ihex.ts#L386

You then mentioned this:

>Turned out codal produces hex files with an extra \n at the end, so trim() ing the hex data fixed the creation problem.

But I the files attached don't have any extra `\n`, was this for a different file?

Just to clarify, micro:bit tooling needs to general hex files with an End Of File record (`:00000001FF`) followed by a new line (`\r\n` or `\n`), or the Intel Hex parsing in DAPLink 0234 doesn't process the record and the file transfer ends up timing out.

-----

>The board IDs should be 9901 for v1 and 9903 for v2. 

Yes, these was the original values, we've recently updated them to 0x9900 and 0x9903 in https://github.com/microbit-foundation/universal-hex/pull/10.

> Usually the v1 file is first.

Yes, this is a now an explicit recommendation in https://github.com/microbit-foundation/universal-hex/pull/10 as well.

-----

> OK, so I now have the generated universal hex file working for v1 targets, but not v2. I have tested extracting the hexes back from the universal one and the extracted files work correctly on both v1 and v2.
> 
> I'm wondering if there's something broken in the generated universal hex file somehow. The latest one is here:
> 
> [ble-open-universal.hex.txt](https://github.com/microbit-foundation/microbit-universal-hex/files/5365504/ble-open-universal.hex.txt)

Do you have the original v1 and v2 portions? I was trying to read back the flash from the nRF52 and could not match them with the original files from your opening message.

Is it possible the original Intel Hex files were using Segmented Linear Address records? I think maybe the library didn't have those records implemented yet (as they have to be converted into Extended Linear Address records).

-----


> * Any stored hexes (all but the first one) have this string added to the beginning of the extracted hex:
> 
> ```
> :020000040000FA
> ```
>
> It doesn't seem to break the hex and is even [taken into account in the tests](https://github.com/microbit-foundation/microbit-universal-hex/blob/master/src/__tests__/universal-hex.spec.ts#L681)

Yes, this is because DAPLink needs the hex file to start with a valid Intel Hex record (not any of the new "customised" records), so in the Universal Hex format we start the file with an Extended Linear Address record (and each 512-byte block also contains starts with it, so that it's fully self-contained) .

When separating the hex files it's not possible to know if the original file started with the Extended Linear Address record or not. Having it at the beginning of the file shouldn't make a difference, as long as it is pointing to the correct address range, and this case `:020000040000FA` is for addresses 0x0000_XXXX.


> * Any `ihex.RecordType.StartLinearAddress` record types are stripped from the extracted hex. Again, this doesn't seem to affect functionality, but I assume it should be added as a [passthrough record type](https://github.com/microbit-foundation/microbit-universal-hex/blob/master/src/universal-hex.ts#L202)

Right, DAPLink basically ignores tthe Start Linear/Segmented Address records, so we excluded them from the Universal Hex format. Is there a good reason to include them?

**Comment by thegecko** [comment]
Thanks @microbit-carlos,

I ended up simply creating a v2 hex file and gave up with universal hex. It may be simpler overall if I simply give you the v1 & v2 files and you can see if you can combine them? I recognise my use case may be unique, so I don't expect this to be a high priority!

- [v1 hex](https://github.com/thegecko/microbit-web-bluetooth/blob/master/hex/ble-open-no-magnet-no-io.hex) - Created with yotta ~18 Months ago
- [v2 hex](https://github.com/thegecko/microbit-web-bluetooth/blob/master/hex/ble-open-microbit-v2.hex) - Created with codal ~1 Month ago

**Comment by microbit-carlos** [comment]
> I recognise my use case may be unique, so I don't expect this to be a high priority!

Quite the opposite, this is a great use case for the tool and exactly the kind of testing we need, so thank you Rob for looking into this and helping us find issues!

Looking at the input hex files the v1 hex uses Extended Linear Address records (good), and the v2 hex uses Segmented Linear Address records, which were not supported in the tool until recent updates.

Having a look at the last [ble-open-universal.hex.txt](https://github.com/microbit-foundation/microbit-universal-hex/files/5365504/ble-open-universal.hex.txt), the Extended Linear Address records in each of the 512-byte blocks is always `:020000040000FA` so that confirms it as the original problem in that hex.

The latest version of the library should be working for these files, you can try it on this page as well: https://microbit-foundation.github.io/microbit-universal-hex/examples/webtool.html

(Looks familiar? We also got to thank you for the inspiration on that page ;)

**Comment by thegecko** [comment]
> The latest version of the library should be working for these files

It did, nice one!

> Looks familiar?

Thanks for the props, the design was done with help from @JoeTheGuitarist

**Comment by microbit-carlos** [comment]
Nice!
And thanks @JoeTheGuitarist!
